name: Analyze with Sonar
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: SonarScanner for .NET 10 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.5.0
      with:
        # The key of the SonarQube project
        sonarProjectKey: phrkdll_weavly
        # The name of the SonarQube project
        sonarProjectName:  weavly
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
        sonarOrganization: phrkdll

  env:
    SONAR_TOKEN: ${{ $SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ $GITHUB_TOKEN }}